import org.jetbrains.kotlin.gradle.dsl.JvmTarget
import org.jetbrains.kotlin.gradle.tasks.KotlinCompilationTask

plugins {
    // Applied globally without versions here to prevent duplicate classpath conflicts
    id "dev.architectury.loom" apply false
    id "org.jetbrains.kotlin.jvm" version "${kotlin_version}" apply false
    id "org.jetbrains.kotlin.plugin.serialization" version "${kotlin_version}" apply false
}

architectury {
    minecraft = rootProject.minecraft_version
}

subprojects {
    apply plugin: "dev.architectury.loom"
    apply plugin: 'org.jetbrains.kotlin.jvm'
    apply plugin: 'org.jetbrains.kotlin.plugin.serialization'

    loom {
        silentMojangMappingsLicense()
    }

    java.toolchain.languageVersion = JavaLanguageVersion.of(21)
    java.withSourcesJar()
    java.withJavadocJar()

    jar {
        from(rootProject.file("LICENSE")) {
            rename { "${it}_${mod_name}" }
        }
        manifest {
            attributes([
                    'Specification-Title'     : mod_name,
                    'Specification-Vendor'    : mod_author,
                    'Specification-Version'   : project.jar.archiveVersion,
                    'Implementation-Title'    : project.name,
                    'Implementation-Version'  : project.jar.archiveVersion,
                    'Implementation-Vendor'   : mod_author,
                    'Implementation-Timestamp': new Date().format("yyyy-MM-dd'T'HH:mm:ssZ"),
                    'Timestamp'               : System.currentTimeMillis(),
                    'Built-On-Java'           : "${System.getProperty('java.vm.version')} (${System.getProperty('java.vm.vendor')})",
                    'Built-On-Minecraft'      : minecraft_version
            ])
        }
    }

    repositories {
        mavenCentral()
        maven {
            name = 'BlameJared Maven (CrT / Bookshelf)'
            url = 'https://maven.blamejared.com'
        }
        maven {
            name = 'cobblemon'
            url = 'https://maven.impactdev.net/repository/development/'
        }
    }

    dependencies {
        minecraft "com.mojang:minecraft:${rootProject.minecraft_version}"
        mappings loom.officialMojangMappings()

        implementation 'org.jetbrains.kotlin:kotlin-reflect'
        implementation platform("org.jetbrains.kotlinx:kotlinx-coroutines-bom:$coroutines_version")
        implementation 'org.jetbrains.kotlinx:kotlinx-coroutines-core-jvm'
        implementation 'org.jetbrains.kotlinx:kotlinx-coroutines-jdk8'

        implementation platform("org.jetbrains.kotlinx:kotlinx-serialization-bom:$serialization_version")
        implementation 'org.jetbrains.kotlinx:kotlinx-serialization-core-jvm'
        implementation 'org.jetbrains.kotlinx:kotlinx-serialization-json-jvm'
    }

    tasks.withType(JavaCompile).configureEach {
        it.options.encoding = 'UTF-8'
        it.options.release = 21
    }

    tasks.withType(KotlinCompilationTask).configureEach {
        compilerOptions {
            javaParameters = true
            jvmTarget = JvmTarget.JVM_21
        }
    }

    tasks.withType(GenerateModuleMetadata).configureEach {
        enabled = false
    }
}