# Project
version=1.0.11-1.7
group=io.github.sirmustfailalot

# Architectury Versions (The Fix)
architectury_loom_version=1.11-SNAPSHOT
architectury_plugin_version=3.4-SNAPSHOT
architectury_api_version=13.0.6

# Common
minecraft_version=1.21.1
minecraft_version_range=[1.21.1, 1.22)
kotlin_version=2.2.10
coroutines_version=1.7.3
serialization_version=1.6.3

# Forge
forge_version=52.0.28
forge_kotlin_version=5.10.0

# Fabric
fabric_version=0.116.6+1.21.1
fabric_loader_version=0.17.2
fabric_kotlin_version=1.13.6+kotlin.2.2.20

# Cobblemon
cobblemon_version=1.7.3+1.21.1

# Mod options
mod_name=ProjectAsh
mod_author=SirMustFailAlot
mod_id=project_ash

# Gradle
org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false