pluginManagement {
    repositories {
        mavenCentral()
        gradlePluginPortal()
        maven {
            name = 'Architectury'
            url = 'https://maven.architectury.dev/'
        }
        maven {
            name = 'Forge'
            url = 'https://maven.minecraftforge.net/'
        }
        maven {
            name = 'Fabric'
            url = 'https://maven.fabricmc.net/'
        }
        maven {
            name = 'cobblemon'
            url = 'https://maven.impactdev.net/repository/development/'
        }
    }
}

plugins {
    id "dev.architectury.loom" version "1.11-SNAPSHOT" apply false
}

rootProject.name = 'ProjectAsh'
include("Common")
include("Fabric")