plugins {
    id 'maven-publish'
}

archivesBaseName = "${mod_name}-forge-${minecraft_version}"

architectury {
    platformSetupLoomIde()
    forge()
}

loom {
    forge {
        mixinConfig "${mod_id}.mixins.json"
    }
}

configurations {
    common
    shadowCommon
    compileClasspath.extendsFrom common
    runtimeClasspath.extendsFrom common
    developmentForge.extendsFrom common
}

dependencies {
    forge "net.minecraftforge:forge:${minecraft_version}-${forge_version}"

    // Kotlin For Forge environment wrapper
    implementation "thedarkcolour:kotlinforforge:$forge_kotlin_version"

    // Architectury API for Forge
    modApi "dev.architectury:architectury-forge:${rootProject.architectury_api_version}"

    // Assuming Cobblemon has a forge module artifact variant
    modImplementation "com.cobblemon:forge:${project.cobblemon_version}"

    common project(path: ":Common", configuration: "namedElements")
    shadowCommon project(path: ":Common", configuration: "transformProductionForge")
}

publishing {
    publications {
        mavenJava(MavenPublication) {
            groupId project.group
            artifactId project.archivesBaseName
            version project.version
            artifact jar
        }
    }
    repositories {
        maven {
            url "file://" + System.getenv("local_maven")
        }
    }
}