plugins {
    id "dev.architectury.loom"
    id 'maven-publish'
}

archivesBaseName = "${mod_name}-common-${minecraft_version}"

architectury {
    common("fabric")
}

dependencies {
    implementation group: 'com.google.code.findbugs', name: 'jsr305', version: '3.0.1'
    implementation("org.json:json:20230618")

    // Cobblemon Fabric is bundled for common compilation tasks if needed,
    modCompileOnly "com.cobblemon:mod:${cobblemon_version}"
}

publishing {
    publications {
        mavenJava(MavenPublication) {
            groupId project.group
            artifactId project.archivesBaseName
            version project.version
            from components.java
        }
    }
    repositories {
        maven {
            url "file://" + System.getenv("local_maven")
        }
    }
}